import ReduxProvider from "@/lib/ReduxProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import NavBar from "@/components/layout/Navbar";
import Footer from "@/components/UI/footer";
import WholeLayout from "@/components/layout/WholeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <StyledComponentsRegistry>
        <html lang="en">
          <body className={inter.className}>
            <WholeLayout>
              <div className="sm:min-h-screen">{children}</div>
            </WholeLayout>
          </body>
        </html>
      </StyledComponentsRegistry>
    </ReduxProvider>
  );
}
